#服务端口号
server:
  port: 8080
  servlet:
    path: /provider
#定义服务名称
spring:
  application:
    #使用 Ribbon 负载均衡的时候服务名中不能使用下划线，不然会找不到服务。
    name: dl-service-provider
  profiles:
    active: local
  cloud:
    #nacos 配置
    nacos:
      #配置 nacos 服务地址
      server-addr: 127.0.0.1:8848
#不用 eureka 了，使用 nacos
#eureka 基本信息配置
#eureka:
#  instance:
#    #注册到 eureka ip 地址
#    hostname: 127.0.0.1
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
#  client:
#    #当前服务注册到 eureka 服务地址
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8100/eureka/,http://${eureka.instance.hostname}:9100/eureka/
#    #将自己注册给自己的注册中心
#    register-with-eureka: true
#    #检索服务