###服务端口号
server:
  port: 8100
##定义服务名称
spring:
  application:
    name: dl-eureka
  profiles:
    active: local
###eureka 基本信息配置
eureka:
  instance:
    ###注册到 eureka ip 地址
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
    ###因为本身是注册中心，是否需要将自己注册给自己的注册中心(集群的时候需要设置成true)
    register-with-eureka: true
    ###因为本身是注册中心,不需要去检索服务(集群的时候需要设置成true)
    fetch-registry: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000


# 注意：1.registerWithEureka和fetchRegistry需要设置成true
#
#      2.defaultZone: http://${eureka.instance.hostname}:9100/eureka/ 
#        9100是另一个注册中心的端口，主要是使用相互注册的原理，如果有第三台机器，在后续添加即可，','逗号隔开。
#
#      3.spring.application. name: dl-eureka   服务的应用名要保持一致，不然会有冲突的问题。